# Laboratorio 1 Python

## <a id='1.0'> 1.0 Types of variables  </a> 


In [4]:
a1 = 3.141
type(a1)

float

In [6]:
# from float to int 

c = int(a2)
type(c)

int

In [7]:
b1 = 10000
type(b1)

int

In [9]:
# from int to float 

float(b1)

10000.0

In [10]:
b2 = 8
type(b2)

int

In [ ]:
# float es número con punto
# Int es número entero
# Para seleccionar varias líneas de código: Shift + teclado hacia abajo

In [14]:
c1 = 'My first python code'  # "My first python code" usando doble comilla
print(c1)  # show that varaible's content
type(c1) # providing varaibles's type 

My first python code


str

In [19]:
# including a space using \n

c1 = "First python code"
c2 = "at R y python Class"
print(c1,'\n',c2)

First python code 
 at R y python Class


In [20]:
# join string 

print(c1 + " : " + c2)

First python code : at R y python Class


In [25]:
# f-string

print(f'{c1} : semester 2022-1')

First python code : semester 2022-1


In [21]:
d = 2022

In [22]:
print(f'{c1} : semester {d}-1')

First python code : semester 2022-1


In [23]:
print('{} : semester {}-1'.format(c1,d))

First python code : semester 2022-1


In [25]:
# Substr elements from string

c1[0:5]

'First'

In [17]:
#first character
print('Fisrt letter is :',c1[0])

Fisrt letter is : F


In [35]:
#first word
print('Fisrt word is :',c1[0:5])

Fisrt word is : First


## <a id='1.2'> 1.2 Boolean  </a> 

It’s used to represent the truth value of an expression.

In [26]:
"a" == "a"

True

In [27]:
1 > 1

False

In [41]:
z1 = (1==1)
z1 

True

In [43]:
int(z1)  # true is 1 in numerical system

1

In [28]:
z2 = (10 > 20) 
int(z2) # false is 0 in numerical system

0

## <a id='1.3'> 1.3 Tuple  </a> 

It is an ordered and immutable Python object

In [11]:
T1 = (1,4,8,10,20,15,4,5,3,8)
####  0,1,2,3,4,...
# Usar corchete para ver la posición
# Usar paréntesis para nombrar

T1[0]

1

In [12]:
# aritmethic operations

print('Suma:', sum(T1),"\n", "Minimo:", min(T1), '\n', "Máximo:", max(T1))

Suma: 78 
 Minimo: 1 
 Máximo: 20


In [53]:
len(T1) # lenght of tuple

10

### Indexing Tuple

In [62]:
T1[0:5] # give us elements from 0 position until 4 position 

(1, 4, 8, 10, 20)

In [30]:
T1[1] # get tuple's element 

4

In [31]:
T1[0:3]


(1, 4, 8)

In [13]:
# It is not possible to change
T1[0] = 4

TypeError: 'tuple' object does not support item assignment

In [14]:
T1[-1]

8

In [16]:
#position
T1.index(8)

2

## <a id='1.4'> 1.4 List  </a> 

#### It is an ordered and mutable Python container.

In [17]:
L1 = []
print(L1)
type(L1)

[]


list

In [18]:
dis1 = ["ATE", 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO']
dis1

['ATE', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO']

In [19]:
dis2 = ['ATE', 'BARRANCO','BREÑA', 'CALLAO', 'CARABAYLLO','CHACLACAYO','CHORRILLOS','CIENEGUILLA'
        ,'COMAS','EL_AGUSTINO','INDEPENDENCIA']

In [33]:
len(dis2)

11

In [20]:
dis2[0] = "CALLAO"
print(dis2)

['CALLAO', 'BARRANCO', 'BREÑA', 'CALLAO', 'CARABAYLLO', 'CHACLACAYO', 'CHORRILLOS', 'CIENEGUILLA', 'COMAS', 'EL_AGUSTINO', 'INDEPENDENCIA']


In [21]:
# Idenxing

dis2[1]

'BARRANCO'

In [22]:
dis2[2:5]   # (5-1=4)

['BREÑA', 'CALLAO', 'CARABAYLLO']

In [83]:
dis2[3:7]

['CALLAO', 'CARABAYLLO', 'CHACLACAYO', 'CHORRILLOS']

In [23]:
dis2[-5:-1]

['CHORRILLOS', 'CIENEGUILLA', 'COMAS', 'EL_AGUSTINO']

In [24]:
num = [13,5,5,8,9,10,5,8,13,1,20]
num.sort()
print(num)

[1, 5, 5, 5, 8, 8, 9, 10, 13, 13, 20]


In [25]:
# append new elements 
# agregar nuevos elementos

num.append(102)
print(num)

[1, 5, 5, 5, 8, 8, 9, 10, 13, 13, 20, 102]


In [26]:
# append new list
# con extend agregamos una nueva lista

num2 = [10,20,30]
num.extend(num2)
print(num)

[1, 5, 5, 5, 8, 8, 9, 10, 13, 13, 20, 102, 10, 20, 30]


In [28]:
print(num.index(102))
# ver la posición del número en la lista

11


In [29]:
print("Suma:", sum(num),'\n', "Minimo:", min(num), '\n', "Máximo:", max(num))

Suma: 259 
 Minimo: 1 
 Máximo: 102


## <a id='1.5'> 1.5 Diccionario  </a> 


In [36]:
Postal_code = {'Majes': 40520, 'Mollendo': 40701, 'Islay': 40704, 'Cotahuasi': 40801, 'Alca': 40802 }

type(Postal_code)

# con diccionarios defines conceptos

dict

In [94]:
Postal_code

{'Majes': 40520,
 'Mollendo': 40701,
 'Islay': 40704,
 'Cotahuasi': 40801,
 'Alca': 40802}

In [53]:
Postal_code.keys()

dict_keys(['Majes', 'Mollendo', 'Islay', 'Cotahuasi', 'Alca'])

In [55]:
# Get information from key
Postal_code['Alca']

40802

In [54]:
# Get information from key
Postal_code.get('Alca')

40802

In [101]:
# Drop key
Postal_code.pop('Islay')
Postal_code

{'Majes': 40520, 'Mollendo': 40701, 'Cotahuasi': 40801, 'Alca': 40802}

In [59]:
# add new elements 

Postal_code.update( { "CHARCANA" :  40803 } )

#diccioanrio dentro de otro diccionario
Postal_code.update( {"LOMAS": {"UBIGEO": 40311, "Poverty Rate" : "18.2%", "Population" : "20 mil"}})


In [60]:
Postal_code

{'Majes': 40520,
 'Mollendo': 40701,
 'Islay': 40704,
 'Cotahuasi': 40801,
 'Alca': 40802,
 'CHARCANA': 40803,
 'LOMAS': {'UBIGEO': 40311, 'Poverty Rate': '18.2%', 'Population': '20 mil'}}

In [61]:
Postal_code.get('LOMAS').get('Poverty Rate')

'18.2%'

In [62]:
Postal_code['LOMAS']['Poverty Rate']

'18.2%'

In [62]:
# keys
cities = ['Fray Martin','Santa Rosa de Puquio','Cuchicorral','Santiago de Punchauca','La Cruz (11 Amigos)','Cerro Cañon','Cabaña Suche','San Lorenzo','Jose Carlos Mariategui','Pascal','La Esperanza','Fundo Pancha Paula','Olfa','Rio Seco','Paraiso','El Rosario','Cerro Puquio','La Campana','Las Animas','Vetancio','Roma Alta','San Jose','San Pedro de Carabayllo','Huacoy','Fundo Pampa Libre','Ex Fundo Santa Ines','Reposo','Carmelito','Santa Elena','Don Luis','Santa Ines Parcela','Asociacion Santa Ines','Roma Baja','Residencial Santa Lucia','San Francisco','Santa Margarita - Molinos','Sipan Peru','Fundo Cuadros','Bello Horizonte','El Hueco','Ex Fundo Mariategui','Naranjito','Vista Hermosa','El Sabroso de Jose Carlos Mariategui','Granja Carabayllo','Agropecuario Valle el Chillon','Camino Real','Copacabana','El Trebol','Tablada la Virgen','San Fernando de Carabayllo','San Fernando de Copacabana','La Manzana','Chacra Grande','Torres de Copacabana','San Pedro de Carabayllo','San Lorenzo','Chaclacayo','Chorrillos','Cieneguilla','Lindero','Pichicato','San Isidro','San Vicente','Piedra Liza','Santa Rosa de Chontay (Chontay)','La Libertad','El Agustino','Independencia','Jesus Maria','La Molina','La Victoria','Lince','Las Palmeras','Chosica','Lurin','Los Almacigos','Rinconada del Puruhuay','Fundo Santa Genoveva','Los Maderos','Casco Viejo','Vista Alegre','Buena Vista Alta','Lomas Pucara','Fundo la Querencia','Magdalena del Mar','Pueblo Libre','Miraflores','Pachacamac','Puente Manchay','Tambo Inga','Pampa Flores','Manchay Alto Lote B','Invasion Cementerio','Manchay Bajo','Santa Rosa de Mal Paso','Cardal','Jatosisa','Tomina','Pucusana','Honda','Quipa','Los Pelicanos','Playa Puerto Bello','Ñaves','Granja Santa Elena','Alvatroz II','Poseidon - Lobo Varado','Playa Minka Mar','Playa Acantilado','Puente Piedra','Punta Hermosa','Capilla Lucumo','Cucuya','Pampapacta','Avicola San Cirilo de Loma Negra - 03','Avicola San Cirilo de Loma Negra - 02','Avicola San Cirilo de Loma Negra - 01','Pampa Mamay','Cerro Botija','Agricultores y Ganaderos','Pampa Malanche Avicola Puma','Punta Negra','Chancheria','Rimac','San Bartolo','Plantel 41','Granja 4','Granja 5','Granja 07','Granja 44','Granja 47','Santa Maria I','Las Torres Santa Fe','San Francisco de Borja','San Isidro','San Juan de Lurigancho','Ciudad de Dios','San Luis','Barrio Obrero Industrial','San Miguel','Santa Anita - los Ficus','Santa Maria del Mar','Don Bruno','Santa Rosa','Santiago de Surco','Surquillo','Villa el Salvador','Villa Maria del Triunfo', 'Pueblo libre']
# values
postal_code1 = [15001,15003,15004,15006,15018,15019,15046,15072,15079,15081,15082,15083,15088,15123,15004,15011,15012,15019,15022,15023,15026,15476,15479,15483,15487,15491,15494,15498,15047,15049,15063,15082,15083,15121,15122,15313,15316,15318,15319,15320,15321,15324,15320,15320,15320,15320,15320,15320,15121,15320,15320,15121,15320,15320,15121,15121,15122,15122,15121,15121,15121,15320,15320,15320,15320,15320,15320,15121,15121,15121,15320,15121,15319,15121,15121,15121,15320,15320,15121,15121,15121,15121,15320,15320,15320,15122,15122,15122,15122,15122,15122,15122,15122,15121,15121,15122,15122,15121,15121,15122,15122,15121,15122,15122,15122,15472,15476,15054,15056,15057,15058,15063,15064,15066,15067,15593,15594,15593,15593,15593,15593,15593,15593,15593,15311,15312,15313,15314,15316,15324,15326,15327,15328,15332,15003,15004,15006,15007,15008,15009,15011,15018,15022,15311,15328,15331,15332,15333,15046, 15001]

In [63]:
# Return a dictionarie
ct_pc = dict( zip( cities , postal_code1) )

In [64]:
ct_pc

{'Fray Martin': 15001,
 'Santa Rosa de Puquio': 15003,
 'Cuchicorral': 15004,
 'Santiago de Punchauca': 15006,
 'La Cruz (11 Amigos)': 15018,
 'Cerro Cañon': 15019,
 'Cabaña Suche': 15046,
 'San Lorenzo': 15122,
 'Jose Carlos Mariategui': 15079,
 'Pascal': 15081,
 'La Esperanza': 15082,
 'Fundo Pancha Paula': 15083,
 'Olfa': 15088,
 'Rio Seco': 15123,
 'Paraiso': 15004,
 'El Rosario': 15011,
 'Cerro Puquio': 15012,
 'La Campana': 15019,
 'Las Animas': 15022,
 'Vetancio': 15023,
 'Roma Alta': 15026,
 'San Jose': 15476,
 'San Pedro de Carabayllo': 15121,
 'Huacoy': 15483,
 'Fundo Pampa Libre': 15487,
 'Ex Fundo Santa Ines': 15491,
 'Reposo': 15494,
 'Carmelito': 15498,
 'Santa Elena': 15047,
 'Don Luis': 15049,
 'Santa Ines Parcela': 15063,
 'Asociacion Santa Ines': 15082,
 'Roma Baja': 15083,
 'Residencial Santa Lucia': 15121,
 'San Francisco': 15122,
 'Santa Margarita - Molinos': 15313,
 'Sipan Peru': 15316,
 'Fundo Cuadros': 15318,
 'Bello Horizonte': 15319,
 'El Hueco': 15320,
 'Ex F

## <a id='1.6'> 1.6 Arrays and Matrix  </a> 


In [38]:
import numpy as np

# A library is a collection of modules or a single module. Libraries are the tools we will use to make our program.

In [39]:
# 1D array (vector)
a = np.array( [1, 2, 3, 4, 5] )
print(a)

[1 2 3 4 5]


In [40]:
type(a)

numpy.ndarray

In [70]:
np.mean(a)

3.0

Standar deviation in Python by default

\begin{equation}
 sd(x) = \sqrt{\frac{\sum(x_i-\bar{x})^2}{N}}
\end{equation}

In [71]:
np.std(a)

1.4142135623730951

Standar deviation in Python by default

\begin{equation}
 sd(x) = \sqrt{\frac{\sum(x_i-\bar{x})^2}{N-1}}
\end{equation}

In [72]:
np.std(a,ddof=1)

1.5811388300841898

In [73]:
# 2D array
M = np.array( [ [1, 2, 3], [4, 5, 6] ] )

print(M)

[[1 2 3]
 [4 5 6]]


In [77]:
# dimensiones

M.shape

(2, 3)

In [78]:
print("Rows:",M.shape[0],"\n", "Columns: ", M.shape[1])


Rows: 2 
 Columns:  3


In [79]:
# Create a 1D NumPy array with values from 0 to 20 (exclusively) incremented by 2:
y = np.arange( 0, 20, 2 )
print(y)

[ 0  2  4  6  8 10 12 14 16 18]


In [48]:
# deafult one by one 

y = np.arange( 1, 11)

print(y)

list(range(11))

[ 1  2  3  4  5  6  7  8  9 10]


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
# rep() equivalent in python

np.repeat(2, 4)
np.repeat(range(11), 4)

np.tile(np.array([1,2]), 4)
np.tile(range(11),5)

# split array

np.array_split(np.arange( 100, 1000),50)

### Matrix

In [49]:
A = np.array([np.arange(0,10), np.arange(10,20), np.arange(30,40), np.arange(-20,-10), np.arange(2,21,2)])

In [50]:
A

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [53]:
A[2:5,:]  # rows selection

# Seleccionar filas

array([[ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [-20, -19, -18, -17, -16, -15, -14, -13, -12, -11],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20]])

In [54]:
A[:,0:6]  # columns selection

# Seleccionar columnas

array([[  0,   1,   2,   3,   4,   5],
       [ 10,  11,  12,  13,  14,  15],
       [ 30,  31,  32,  33,  34,  35],
       [-20, -19, -18, -17, -16, -15],
       [  2,   4,   6,   8,  10,  12]])

In [56]:
M1 = np.zeros( (8, 2) )
print(M1)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [57]:
M2 = np.ones( (8, 4) )
print(M2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Join matrix

In [58]:
M3 = np.hstack((M1,M2))  # stack horizontal 
M3

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

In [59]:
M4 = np.array([[2,2,3,4,5,1],[1,5,5,9,8,2]])
print(M4)

[[2 2 3 4 5 1]
 [1 5 5 9 8 2]]


In [60]:
M5 = np.vstack((M3,M4)) # stack vertical 
print(M5)
M5.T

[[0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [2. 2. 3. 4. 5. 1.]
 [1. 5. 5. 9. 8. 2.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 2., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2., 5.],
       [1., 1., 1., 1., 1., 1., 1., 1., 3., 5.],
       [1., 1., 1., 1., 1., 1., 1., 1., 4., 9.],
       [1., 1., 1., 1., 1., 1., 1., 1., 5., 8.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 2.]])

In [61]:
# Create a 1D NumPy array of ones of length 10:
w = np.ones(10)
print(w)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [62]:
# Create the identity matrix of size 8:
I = np.eye(8)
print(I)

[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [63]:
I3 = I.reshape(32, 2)
print(I3)

[[1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 1.]]


In [77]:
import random 

random.seed(175) # semilla aleatoria

np.random.rand(500)

array([0.24731131, 0.28671371, 0.99282501, 0.75172088, 0.712826  ,
       0.33032713, 0.9803622 , 0.98765837, 0.91945259, 0.32731286,
       0.56195897, 0.24385205, 0.42400369, 0.10620554, 0.26031169,
       0.47442559, 0.95146593, 0.91637709, 0.80634235, 0.82455417,
       0.24666605, 0.80951086, 0.27849759, 0.67661227, 0.42897417,
       0.84618919, 0.70897624, 0.43453072, 0.8494031 , 0.35995841,
       0.07139095, 0.32218999, 0.28786225, 0.25998424, 0.6105984 ,
       0.70492127, 0.2849689 , 0.14995164, 0.23301186, 0.92058755,
       0.31554928, 0.99397333, 0.99449213, 0.18260955, 0.19618338,
       0.84354754, 0.61091378, 0.70992719, 0.29839665, 0.53024345,
       0.79629586, 0.67343615, 0.84716553, 0.25429286, 0.78773915,
       0.38860766, 0.07201931, 0.40556793, 0.64417147, 0.74170174,
       0.8127351 , 0.13601158, 0.0817221 , 0.19640368, 0.9496781 ,
       0.89044484, 0.95614329, 0.83459753, 0.10233407, 0.1706093 ,
       0.0773725 , 0.24621017, 0.2541718 , 0.20447364, 0.38455

In [78]:
import random 

random.seed(175) # semilla aleatoria

x1 = np.random.rand(500) # uniform distribution  [0,1]
x2 = np.random.rand(500) # uniform distribution [0,1]
x3 = np.random.rand(500) # uniform distribution [0,1]
x4 = np.random.rand(500) # uniform distribution [0,1]
e = np.random.normal(0,1,500) # normal distribution mean = 0 and sd = 1

# Poblacional regression (Data Generating Process GDP)


Y = 1 + 0.8*x1 + 1.2*x2 + 0.5*x3 + 1.5*x4 + e

In [97]:
X = np.column_stack((np.ones(500),x1,x2,x3,x4))
X

array([[1.        , 0.15202709, 0.16545865, 0.19223446, 0.2183345 ],
       [1.        , 0.88867204, 0.13073635, 0.63118029, 0.26001309],
       [1.        , 0.84935949, 0.73861047, 0.21451097, 0.77371957],
       ...,
       [1.        , 0.85611886, 0.8475847 , 0.62436872, 0.83069675],
       [1.        , 0.30604432, 0.56793648, 0.23565967, 0.52384759],
       [1.        , 0.71393431, 0.13937224, 0.11756261, 0.15967947]])

In [99]:
beta = np.linalg.inv(X.T @ X) @ ((X.T) @ Y )
print(beta)

[0.92520163 0.62337203 1.18403152 0.7290729  1.450006  ]


# References

## Numpy 
https://numpy.org/doc/stable/reference/arrays.html

https://www.kaggle.com/code/hkumls/intensive-python-tutorial-numpy/notebook